Remove vulnerability in velocity-dependency
navikt/isdialogmote pull request #456
Opened 2023-07-11 09:54 UTC by eirikdahlen

From https://github.com/advisories/GHSA-59j4-wjwp-mw9m

Litt usikker på om dette funker, ref Geir sitt forsøk i januar: https://github.com/navikt/isdialogmote/pull/402

CXF v4.0.2 har den riktige velocity-pakken, men da får man problemer mot opensaml 🤷🏼‍♂️

2023-07-11 09:55 UTC, eirikdahlen commented on build.gradle.kts
> +        }
Feilen er fikset i velocity-engine-core 2.3, mens man via CXF 4.0.2 bare får velocity-engine-core 2.2, så måtte bumpe den manuelt 😕

2023-07-11 09:56 UTC, eirikdahlen commented on build.gradle.kts
> +                strictly("4.0.1")
Den prøver å finne opensaml 4.0.2, men den eksisterer ikke på maven central, så prøver 4.0.1

2023-07-12 06:54 UTC, geir-waagboe commented
Må finne et test-case i dev der vi faktisk forsøker å kalle altinn for å sende varsel til arbeidsgiver. Usikker på hvordan man gjør det i dev.

2023-08-01 08:44 UTC, andersrognstad approved these changes

2023-08-01 10:34 UTC, andersrognstad commented
Fikk testet denne i dev nå med dialogmøteinnkalling på 25830399413 (måtte deploye en versjon med altinn-sending enabled i naiserator-dev-fila, da vi har skrudd av dette pga valideringsfeil fra altinn på orgnr). Får følgende feil med oppgradert bibliotek:
``
jakarta.xml.ws.WebServiceException: Could not find wsdl:binding operation info for web method insertCorrespondenceBasicV2.
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:129)
	at jdk.proxy2/jdk.proxy2.$Proxy25.insertCorrespondenceBasicV2(Unknown Source)
	at no.nav.syfo.client.altinn.AltinnClient.sendToVirksomhet(AltinnClient.kt:17)
	at no.nav.syfo.dialogmote.VarselService.sendVarsel(VarselService.kt:71)
``
Med bibliotek-versjonen på `master` får man sendt til altinn, men får valideringsfeil i respons:
`Error fra altinn VALIDATION_FAILED for virksomhetsbrevId: f0cd4d29-7d06-4222-8953-9c1dbee0957b, Invalid Reportee  :  972674818`

2023-08-01 10:36 UTC, andersrognstad requested changes
Må fikse` jakarta.xml.ws.WebServiceException: Could not find wsdl:binding operation info for web method insertCorrespondenceBasicV2. at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:129)`

2023-08-15 08:35 UTC, eirikdahlen commented
Hmm okey, takk for at du testet! 👌🏼 Kan få sett på det etterhvert, men synes det var litt mye hassle for å få fikset dette 😕

2023-08-18 09:43 UTC, geir-waagboe commented on build.gradle.kts
> +    const val cxfVersion = "4.0.2"
Ser at det nå har kommet noen nye 3.*-versjoner (feks 3.5.6 og 3.6.1). Kanskje vi kan forsøke en av dem i stedet?

2023-08-24 11:47 UTC, eirikdahlen commented
Lukker denne foreløpig, da vi ikke har noen tilfredsstillende løsninger per nå 😞

2023-08-24 11:47 UTC, closed without merging